name: SOOS DAST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  soos_dast:
    name: Run SOOS DAST
    runs-on: ubuntu-latest
    container:
      image: soosio/dast:latest
    steps:
      - name: Run SOOS DAST Analysis
        id: soos-dast-analysis
        working-directory: /zap
        run: |
          python3 main.py --clientId="$client_id" --apiKey="$api_key" --projectName="$project_name" --scanMode="$scan_mode" --apiURL="$api_url" --branchName="$branch_name" --commitHash="$commit_hash" --sarif=True --gpat="$gpat" $target_url
        env:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: "soos-ent/github-demo"
          branch_name: ${{ github.ref }}
          commit_hash: ${{ github.sha }}
          scan_mode: "baseline"
          api_url: "https://api.soos.io/api/"
          target_url: "https://brokencrystals.com/"
          gpat: ${{ secrets.SOOS_GITHUB_PAT }}
          
  soos_sca:
    name: SOOS SCA Scan
    runs-on: ubuntu-latest
    steps:
      - uses: soos-io/soos-sca-github-action@v1.0.3-beta
        name: SOOS SCA Scan
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: ${{ github.repository }}
          branch_name: ${{ github.ref }}
          commit_hash: ${{ github.sha }}
          sarif: true
          gpat: ${{ secrets.SOOS_GITHUB_PAT }}
